# 
FROM python:3.11
#
ARG DATOX_DATABASE__MAIN_DSN
ENV DATOX_DATABASE__MAIN_DSN $DATOX_DATABASE__MAIN_DSN
ARG DATOX_DATABASE__ADMIN_DSN
ENV DATOX_DATABASE__ADMIN_DSN $DATOX_DATABASE__ADMIN_DSN
ARG ALLOWED_ORIGINS
ENV ALLOWED_ORIGINS $ALLOWED_ORIGINS
ARG AZURE_AD_INSTANCE
ENV AZURE_AD_INSTANCE $AZURE_AD_INSTANCE
ARG AZURE_AD_DOMAIN
ENV AZURE_AD_DOMAIN $AZURE_AD_DOMAIN
ARG AZURE_AD_TENANT_ID
ENV AZURE_AD_TENANT_ID $AZURE_AD_TENANT_ID
ARG AZURE_AD_CLIENT_ID
ENV AZURE_AD_CLIENT_ID $AZURE_AD_CLIENT_ID
ARG AZURE_AD_FRONTEND_CLIENT_ID
ENV AZURE_AD_FRONTEND_CLIENT_ID $AZURE_AD_FRONTEND_CLIENT_ID
ARG AZURE_STORAGE_CONNECTION_STRING
ENV AZURE_STORAGE_CONNECTION_STRING $AZURE_STORAGE_CONNECTION_STRING
ARG AZURE_STORAGE_DA_AGENT_CONTAINER
ENV AZURE_STORAGE_DA_AGENT_CONTAINER $AZURE_STORAGE_DA_AGENT_CONTAINER
ARG AZURE_OPENAI_ENDPOINT
ENV AZURE_OPENAI_ENDPOINT $AZURE_OPENAI_ENDPOINT
ARG OPENAI_API_VERSION
ENV OPENAI_API_VERSION $OPENAI_API_VERSION
ARG AZURE_OPENAI_API_KEY
ENV AZURE_OPENAI_API_KEY $AZURE_OPENAI_API_KEY

WORKDIR /code
# 
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /code/app
# only for local tests
# COPY ./.env /code/.env
COPY ./migrations /code/migrations
COPY ./alembic.ini /code/alembic.ini
# only for local tests
# COPY ./SSL /code/SSL

RUN alembic -n admin upgrade head
RUN alembic -n main upgrade head

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
