"""changed blob id to blob name

Revision ID: 2063f0fdc474
Revises: 75264556f431
Create Date: 2024-03-29 16:07:16.223961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2063f0fdc474"
down_revision: Union[str, None] = "75264556f431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("icon_file_name", sa.String(), nullable=True))
    op.drop_column("assistants", "icon_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("icon_id", postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column("assistants", "icon_file_name")
    # ### end Alembic commands ###
