"""added warehouses

Revision ID: 2c4a23b21c89
Revises: fdedf45f666b
Create Date: 2024-01-31 21:44:35.060970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c4a23b21c89"
down_revision: Union[str, None] = "fdedf45f666b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snowflake_warehouses",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("modified_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("identifier_id", postgresql.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier_id"),
        info={"dbname": "main"},
    )
    op.drop_column("snowflake_identifiers", "warehouse")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snowflake_identifiers", sa.Column("warehouse", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table("snowflake_warehouses")
    # ### end Alembic commands ###
