"""Add sql query field to message

Revision ID: 4ba0e1860131
Revises: daa8b705b617
Create Date: 2024-01-17 18:03:07.284049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ba0e1860131"
down_revision: Union[str, None] = "daa8b705b617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("sql_query", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "sql_query")
    # ### end Alembic commands ###
