"""Create chat and messages

Revision ID: 4dac0f65402b
Revises: 
Create Date: 2023-12-26 19:50:01.113157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dac0f65402b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Analytics', 'FileSearch', name='chattype'), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('chat_model', sa.Enum('GPT3', 'GPT3_16K', name='chatmodel'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('messages',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Error', 'Success', 'Cancelled', 'Pending', name='messagestatus'), nullable=True),
    sa.Column('role', sa.Enum('System', 'User', 'Assistant', 'Function', name='messagerole'), nullable=True),
    sa.Column('follow_up_questions', sa.String(), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
