"""Create file and other models

Revision ID: 54bd53a8ea09
Revises: 4dac0f65402b
Create Date: 2023-12-27 17:32:11.272795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bd53a8ea09'
down_revision: Union[str, None] = '4dac0f65402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('blobName', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('snowflake_identifiers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_files',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_sharepoint_documents',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_path', sa.String(), nullable=False),
    sa.Column('item_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('item_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.add_column('messages', sa.Column('chat_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'messages', ['prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'prompt_id')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'chat_id')
    op.drop_table('message_sharepoint_documents')
    op.drop_table('message_files')
    op.drop_table('snowflake_identifiers')
    op.drop_table('files')
    # ### end Alembic commands ###
