"""Added DataAnalytics to chat type

Revision ID: 56ef6b130896
Revises: 570a327388b4
Create Date: 2024-01-25 17:31:18.568531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ef6b130896'
down_revision: Union[str, None] = '570a327388b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snowflake_identifiers', sa.Column('account_identifier', sa.String(), nullable=False))
    op.add_column('snowflake_identifiers', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('snowflake_identifiers', sa.Column('client_secret', sa.String(), nullable=False))
    op.add_column('snowflake_identifiers', sa.Column('token_endpoint', sa.String(), nullable=False))
    op.drop_column('snowflake_identifiers', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snowflake_identifiers', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('snowflake_identifiers', 'token_endpoint')
    op.drop_column('snowflake_identifiers', 'client_secret')
    op.drop_column('snowflake_identifiers', 'client_id')
    op.drop_column('snowflake_identifiers', 'account_identifier')
    # ### end Alembic commands ###
