"""added chat_snowflake_data

Revision ID: 570a327388b4
Revises: f9e19e793c15
Create Date: 2024-01-24 17:51:40.339938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570a327388b4'
down_revision: Union[str, None] = 'f9e19e793c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_snowflake_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('snowflake_account', sa.String(), nullable=True),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.add_column('chats', sa.Column('snowflake_data_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'chats', 'chat_snowflake_data', ['snowflake_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'snowflake_data_id')
    op.drop_table('chat_snowflake_data')
    # ### end Alembic commands ###
