"""Added stored file ID field to message

Revision ID: 58782fd67155
Revises: 4ba0e1860131
Create Date: 2024-01-18 16:59:12.010203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58782fd67155'
down_revision: Union[str, None] = '4ba0e1860131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('stored_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'stored_file_id')
    # ### end Alembic commands ###
