"""changed iden id not unique

Revision ID: 665097ad601b
Revises: c22a968a70f7
Create Date: 2024-02-01 16:48:30.827472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665097ad601b'
down_revision: Union[str, None] = 'c22a968a70f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('snowflake_warehouses_identifier_id_key', 'snowflake_warehouses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('snowflake_warehouses_identifier_id_key', 'snowflake_warehouses', ['identifier_id'])
    # ### end Alembic commands ###
