"""added assistant to chat type 2

Revision ID: 68ad33a92fca
Revises: d8eef187b545
Create Date: 2024-03-27 22:05:42.118195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68ad33a92fca"
down_revision: Union[str, None] = "d8eef187b545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE chattype ADD VALUE 'Assistant'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
