"""added message assistant document and blob name for assistant file

Revision ID: 75264556f431
Revises: dc0c3d650582
Create Date: 2024-03-29 12:16:47.926130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75264556f431'
down_revision: Union[str, None] = 'dc0c3d650582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistantFiles', sa.Column('blob_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistantFiles', 'blob_name')
    # ### end Alembic commands ###
