"""Added assistant to chat

Revision ID: 75ab1f0a62ee
Revises: 75a15170877f
Create Date: 2024-03-27 14:25:07.971172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ab1f0a62ee'
down_revision: Union[str, None] = '75a15170877f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('assistant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'assistants', ['assistant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'assistant_id')
    # ### end Alembic commands ###
