"""Added user role to snowflake identifier

Revision ID: 9150207c7037
Revises: ab8465bc8a3f
Create Date: 2024-02-23 15:18:46.449040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9150207c7037'
down_revision: Union[str, None] = 'ab8465bc8a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snowflake_identifiers', sa.Column('user_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snowflake_identifiers', 'user_role')
    # ### end Alembic commands ###
