"""added thread id to chat

Revision ID: a73cce2aa60d
Revises: 9150207c7037
Create Date: 2024-03-08 19:04:44.642255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73cce2aa60d'
down_revision: Union[str, None] = '9150207c7037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('assistant_thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'assistant_thread_id')
    # ### end Alembic commands ###
