"""added choice field to messages

Revision ID: ab8465bc8a3f
Revises: 665097ad601b
Create Date: 2024-02-21 17:04:36.400300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab8465bc8a3f"
down_revision: Union[str, None] = "665097ad601b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("file_name", sa.String(), nullable=False))
    op.add_column("files", sa.Column("blob_name", sa.String(), nullable=False))
    op.add_column("files", sa.Column("file_extension", sa.String(), nullable=False))
    op.drop_column("files", "fileName")
    op.drop_column("files", "blobName")
    op.add_column("messages", sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        """
        ALTER TABLE messages 
        ALTER COLUMN follow_up_questions TYPE JSONB 
        USING follow_up_questions::jsonb
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "follow_up_questions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("messages", "choices")
    op.add_column("files", sa.Column("blobName", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("files", sa.Column("fileName", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("files", "file_extension")
    op.drop_column("files", "blob_name")
    op.drop_column("files", "file_name")
    # ### end Alembic commands ###
