"""make shareopint size nullable

Revision ID: aee2c0d162d5
Revises: a73cce2aa60d
Create Date: 2024-03-14 20:57:56.018046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aee2c0d162d5"
down_revision: Union[str, None] = "a73cce2aa60d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message_sharepoint_documents", "item_size", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message_sharepoint_documents", "item_size", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
