"""added warehouses

Revision ID: d2e41b52fd8a
Revises: 2c4a23b21c89
Create Date: 2024-01-31 21:53:04.941579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2e41b52fd8a"
down_revision: Union[str, None] = "2c4a23b21c89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "snowflake_warehouses", "snowflake_identifiers", ["identifier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "snowflake_warehouses", type_="foreignkey")
    # ### end Alembic commands ###
