"""Added assistant type to  chat type

Revision ID: d8eef187b545
Revises: f9ebb458220c
Create Date: 2024-03-27 16:41:49.905003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8eef187b545'
down_revision: Union[str, None] = 'f9ebb458220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats", 
        "type", 
        existing_type=sa.Enum("Analytics", "FileSearch", "DataAnalytics", name="chattype"), 
        type_=sa.Enum("Analytics", "FileSearch", "DataAnalytics", "Assistant", name="chattype"), 
    )
        # sa.Column("type", sa.Enum("Analytics", "FileSearch", "DataAnalytics", name="chattype"), nullable=True),

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats", 
        "type", 
        existing_type=sa.Enum("Analytics", "FileSearch", "DataAnalytics", "Assistant", name="chattype"), 
        type_=sa.Enum("Analytics", "FileSearch", "DataAnalytics", name="chattype"), 
    )
    # ### end Alembic commands ###
