"""added icon field for assistant

Revision ID: dc0c3d650582
Revises: 68ad33a92fca
Create Date: 2024-03-28 15:12:20.572658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc0c3d650582"
down_revision: Union[str, None] = "68ad33a92fca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("icon_id", postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "icon_id")
    # ### end Alembic commands ###
