"""First

Revision ID: f9e19e793c15
Revises: 
Create Date: 2024-01-22 18:36:09.254117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9e19e793c15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Analytics', 'FileSearch', 'DataAnalytics', name='chattype'), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('chat_model', sa.Enum('GPT3', 'GPT3_16K', 'GPT4_32K', name='chatmodel'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('blobName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('snowflake_identifiers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Error', 'Success', 'Cancelled', 'Pending', name='messagestatus'), nullable=True),
    sa.Column('role', sa.Enum('System', 'User', 'Assistant', 'Function', name='messagerole'), nullable=True),
    sa.Column('follow_up_questions', sa.String(), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('sql_query', sa.String(), nullable=True),
    sa.Column('stored_file_id', sa.String(), nullable=True),
    sa.Column('reply_to_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('prompt_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_sharepoint_documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_path', sa.String(), nullable=False),
    sa.Column('item_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('item_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_sharepoint_documents')
    op.drop_table('message_files')
    op.drop_table('messages')
    op.drop_table('snowflake_identifiers')
    op.drop_table('files')
    op.drop_table('chats')
    # ### end Alembic commands ###
