"""Added assistant to chat

Revision ID: f9ebb458220c
Revises: 75a15170877f
Create Date: 2024-03-27 14:28:07.425546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9ebb458220c"
down_revision: Union[str, None] = "75a15170877f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("assistant_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "chats", "assistants", ["assistant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.drop_column("chats", "assistant_id")
    # ### end Alembic commands ###
