"""changed snowflake identifier

Revision ID: fdedf45f666b
Revises: 56ef6b130896
Create Date: 2024-01-26 21:19:56.931302

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fdedf45f666b"
down_revision: str | None = "56ef6b130896"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snowflake_identifiers", sa.Column("authorization_endpoint", sa.String(), nullable=False))
    op.add_column("snowflake_identifiers", sa.Column("warehouse", sa.String(), nullable=True))
    op.alter_column("snowflake_identifiers", "user_id", existing_type=postgresql.UUID(), nullable=True)
    op.create_unique_constraint(None, "snowflake_identifiers", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "snowflake_identifiers", type_="unique")
    op.alter_column("snowflake_identifiers", "user_id", existing_type=postgresql.UUID(), nullable=False)
    op.drop_column("snowflake_identifiers", "warehouse")
    op.drop_column("snowflake_identifiers", "authorization_endpoint")
    # ### end Alembic commands ###
