"""Add identity tables

Revision ID: eee32b2b6241
Revises:
Create Date: 2024-01-22 18:35:04.718634

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eee32b2b6241"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"dbname": "admin"},
    )
    op.create_table(
        "tenants",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("azure_object_id", sa.String(), nullable=False),
        sa.Column("tenant_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        info={"dbname": "admin"},
    )
    op.create_table(
        "application_users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("azure_object_id", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"dbname": "admin"},
    )
    op.create_index(
        op.f("ix_application_users_azure_object_id"), "application_users", ["azure_object_id"], unique=True
    )
    op.create_table(
        "user_roles",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("role_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["application_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"dbname": "admin"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_application_users_azure_object_id"), table_name="application_users")
    op.drop_table("application_users")
    op.drop_table("tenants")
    op.drop_table("roles")
    # ### end Alembic commands ###
