"""added azure role id

Revision ID: f75a352e28be
Revises: eee32b2b6241
Create Date: 2024-02-26 17:30:05.779266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75a352e28be'
down_revision: Union[str, None] = 'eee32b2b6241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('azure_role_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_roles_azure_role_id'), 'roles', ['azure_role_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_azure_role_id'), table_name='roles')
    op.drop_column('roles', 'azure_role_id')
    # ### end Alembic commands ###
