"""Add identity tables

Revision ID: fb33725a6c02
Revises: e66e43c8a36f
Create Date: 2023-12-27 17:38:43.486100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb33725a6c02'
down_revision: Union[str, None] = 'e66e43c8a36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('azure_object_id', sa.String(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'admin'}
    )
    op.create_table('application_users',
    sa.Column('azure_object_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'admin'}
    )
    op.create_index(op.f('ix_application_users_azure_object_id'), 'application_users', ['azure_object_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['application_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'admin'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_application_users_azure_object_id'), table_name='application_users')
    op.drop_table('application_users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
