"""First

Revision ID: 5ce6e65245ee
Revises: 
Create Date: 2024-01-26 17:04:38.355438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce6e65245ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_snowflake_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('snowflake_account', sa.String(), nullable=True),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('blobName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('snowflake_identifiers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('account_identifier', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('token_endpoint', sa.String(), nullable=False),
    sa.Column('authorization_endpoint', sa.String(), nullable=False),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    info={'dbname': 'main'}
    )
    op.create_table('chats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Analytics', 'FileSearch', 'DataAnalytics', name='chattype'), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('chat_model', sa.Enum('GPT3', 'GPT3_16K', 'GPT4_32K', name='chatmodel'), nullable=True),
    sa.Column('snowflake_data_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['snowflake_data_id'], ['chat_snowflake_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('pinned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Error', 'Success', 'Cancelled', 'Pending', name='messagestatus'), nullable=True),
    sa.Column('role', sa.Enum('System', 'User', 'Assistant', 'Function', name='messagerole'), nullable=True),
    sa.Column('follow_up_questions', sa.String(), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('sql_query', sa.String(), nullable=True),
    sa.Column('stored_file_id', sa.String(), nullable=True),
    sa.Column('reply_to_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('prompt_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    op.create_table('message_sharepoint_documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_path', sa.String(), nullable=False),
    sa.Column('item_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('item_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'dbname': 'main'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_sharepoint_documents')
    op.drop_table('message_files')
    op.drop_table('messages')
    op.drop_table('chats')
    op.drop_table('snowflake_identifiers')
    op.drop_table('files')
    op.drop_table('chat_snowflake_data')
    # ### end Alembic commands ###
