name: Deploy Copilot Python Backend to Azure App Service Action

on:
  push:
    branches:
      - main  
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Push the Docker image to ACR
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
      
      - name: Build and Push the Docker image to ACR
        run: |
            docker build \
              --build-arg DATOX_DATABASE__MAIN_DSN=${{ secrets.DATOX_DATABASE__MAIN_DSN }} \
              --build-arg DATOX_DATABASE__ADMIN_DSN=${{ secrets.DATOX_DATABASE__ADMIN_DSN }} \
              --build-arg ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
              --build-arg AZURE_AD_INSTANCE=${{ secrets.AZURE_AD_INSTANCE }} \
              --build-arg AZURE_AD_DOMAIN=${{ secrets.AZURE_AD_DOMAIN }} \
              --build-arg AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }} \
              --build-arg AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }} \
              --build-arg AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }} \
              --build-arg AZURE_AD_FRONTEND_CLIENT_ID=${{ secrets.AZURE_AD_FRONTEND_CLIENT_ID }} \
              --build-arg AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
              --build-arg AZURE_STORAGE_DA_AGENT_CONTAINER=${{ secrets.AZURE_STORAGE_DA_AGENT_CONTAINER }} \
              --build-arg AZURE_STORAGE_FILE_CONTAINER=${{ secrets.AZURE_STORAGE_FILE_CONTAINER }} \
              --build-arg GPT4_TURBO_AZURE_OPENAI_ENDPOINT=${{ secrets.GPT4_TURBO_AZURE_OPENAI_ENDPOINT }} \
              --build-arg GPT4_TURBO_OPENAI_API_VERSION=${{ secrets.GPT4_TURBO_OPENAI_API_VERSION }} \
              --build-arg GPT4_TURBO_AZURE_OPENAI_API_KEY=${{ secrets.GPT4_TURBO_AZURE_OPENAI_API_KEY }} \
              --build-arg GPT4_TURBO_DEPLOYMENT_NAME=${{ secrets.GPT4_TURBO_DEPLOYMENT_NAME }} \
              --build-arg AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME }} \
              --build-arg AZURE_COGNITIVE_SEARCH_SERVICE_NAME=${{ secrets.AZURE_COGNITIVE_SEARCH_SERVICE_NAME }} \
              --build-arg AZURE_COGNITIVE_SEARCH_SHAREPOINT_INDEX_NAME=${{ secrets.AZURE_COGNITIVE_SEARCH_SHAREPOINT_INDEX_NAME }} \
              --build-arg AZURE_COGNITIVE_SEARCH_API_KEY=${{ secrets.AZURE_COGNITIVE_SEARCH_API_KEY }} \
              --build-arg AZURE_COGNITIVE_SEARCH_INDEX_URL=${{ secrets.AZURE_COGNITIVE_SEARCH_INDEX_URL }} \
              --build-arg RAG_AZURE_ASSISTANT_ID=${{ secrets.RAG_AZURE_ASSISTANT_ID }} \
              --build-arg AZURE_STORAGE_DA_ASSISTANT_AGENT_CONTAINER=${{ secrets.AZURE_STORAGE_DA_ASSISTANT_AGENT_CONTAINER }} \
              --build-arg SQL_ANALYTIC_AZURE_ASSISTANT_ID=${{ secrets.SQL_ANALYTIC_AZURE_ASSISTANT_ID }} \
              --build-arg CHATGPT_AGENT_AZURE_ASSISTANT_ID=${{ secrets.CHATGPT_AGENT_AZURE_ASSISTANT_ID }} \
              --build-arg GPT4_ASSISTANT_OPENAI_API_VERSION=${{ secrets.GPT4_ASSISTANT_OPENAI_API_VERSION }} \
              -t ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/copilot-backend:${{ github.run_id }} .

            docker push ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/copilot-backend:${{ github.run_id }}          
  
  # staging:
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: staging 
  #   name: "[STAGING] Pull and Deploy App Service"
  #   steps:
  #     - uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'NewCopilotWebApi'
  #         slot-name: newcopilotwebapi-staging
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
  #         images: '${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/copilot-backend:${{ github.run_id }}'

  production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    environment: prod 
    name: "[PROD] Pull and Deploy App Service"
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'NewCopilotWebApi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/copilot-backend:${{ github.run_id }}'
            
